apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: bocak95/ambulance-ufe
  newName: bocak95/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20250311.1137 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
